

export const appPath = {
  ROOT: "/",
  HOME: "/",
  ABOUT: "about",
  PRODUCTS: "products",
  PRODUCTS_DETAILS: "products/:id",
  PRODUCTS_CATEGORY: "products/category/data",
  CONTACT: "contact",
  LOGIN: "login",
  SIGNUP: "signup",
  CART: "cart",
  FAVORITE: "favorites",
  FORGOT_PASSWORD: "forgot-password",
  CHECKOUT: "/checkout",
  ORDER_SUCCESS: "order-success",
  PROFILE_MANAGE: "profile/manage",
  PROFILE_VERIFY: "verify-email",
  USER_ORDERS: "profile/orders",
  USER_ORDERS_CANCELLATIONS: "profile/orders-cancellations",
  USER_REVIEWS: "profile/reviews",
  ADMIN: "admin",
  ADMIN_PRODUCTS: "admin/products",
  ADMIN_ORDERS: "admin/orders",
  ADMIN_USERS: "admin/users",
  ADMIN_PRODUCT_CREATE: "admin/products/create",
  ADMIN_PRODUCT_DELETE: "admin/products/delete/:id",
  ADMIN_PRODUCT_UPDATE_STATUS: "admin/products/update-status/:id",
  ADMIN_PRODUCT_UPDATE_STOCK: "admin/products/update-stock/:id",
  ADMIN_PRODUCT_UPDATE_IMAGE: "admin/products/update-image/:id",
  ADMIN_PRODUCT_UPDATE_PRICE: "admin/products/update-price/:id",
  ADMIN_PRODUCT_EDIT: "admin/products/edit/:id",
  ADMIN_ORDER_DETAILS: "admin/orders/details/:id",
  ADMIN_USER_EDIT: "admin/users/edit/:id",
  ADMIN_USER_CREATE: "admin/users/create",
  ADMIN_USER_DELETE: "admin/users/delete/:id",
  ADMIN_ORDER_DELETE: "admin/orders/delete/:id",
  ADMIN_ORDER_SHIP: "admin/orders/ship/:id",
  ADMIN_ORDER_RETURN: "admin/orders/return/:id",
  ADMIN_ORDER_CANCEL: "admin/orders/cancel/:id",
  ADMIN_ORDER_RETURN_REQUEST: "admin/orders/return-request/:id",
};
